---
title: "case study 08"
author: "Tevye Davis"
date: "10/29/2022"
output: 
  html_document: default
  github_document: default
  powerpoint_presentation: default
  word_document: default
---

  
```{r ,echo = FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(kableExtra)
library(magick)

table<-read_table("ftp://aftp.cmdl.noaa.gov/products/trends/co2/co2_annmean_mlo.txt", skip = 57)
colnames(table) <-c("year", "mean", "unc")
#view(table)
```

```{r}
m<-ggplot(table, aes(x=year, y=mean))+
  geom_line(color="red", size= 2)+
  labs(x="year", y="Mauna Loa Annual Mean CO_2 (ppm)", title="Annual Mean Carbon Dioxide Concentrations 1959-Present")

m
```

```{r}
top5<-arrange(table, desc(mean))[1:5, ]
knitr::kable(top5, caption = 'Top Five Annual Mean Carbon Dioxide Concentrations at Mona Loa',
             col.names = c("year", "mean", "unc")) %>%
  as_image(width = 10,file = "table.png")

rmarkdown::render("case_study_08.Rmd", output_format = "all") 
```
rmarkdown::render("case_study_08.Rmd", output_format = "all") 

